name: Release

on:
  push:
    tags:
      - 'releases/*.*.*'

jobs:

  testing:
    uses: ./github/workflows/testing.yml

  release:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: "checking vars 1"
        run: echo "${GITHUB_REF}"

      - name: "checking vars 2"
        run: echo "${GITHUB_REF#refs/tags/releases/}"

      - name: "checking vars 3"
        run: echo "${GITHUB_EVENT_WORKFLOW_RUN_HEAD_BRANCH#releases/}"

      - name: checking vars 4
        run: echo "${GITHUB_EVENT_WORKFLOW_RUN_HEAD_REF}"

      - name: checking vars 5
        run: echo "${GITHUB_EVENT_WORKFLOW_RUN_HEAD_REF#releases/}"

      - name: running some deploy release
        run: echo "running some deploy release"

      - name: debug event
        run: cat "$GITHUB_EVENT_PATH"

      - name: retrieving release_version
        run: |
          TAG=$(jq -r '.workflow_run.head_branch' "$GITHUB_EVENT_PATH")
          echo "tag=$TAG"
          echo "version=${TAG#releases/}"

      - name: Use the release tag name
        run: echo "The release number is ${{ github.event.release.tag_name }}"