name: Tests

on:
  push:
    tags:
      - 'releases/*.*.*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: run test
        run: php index.php